name: sharpy
channels:
- ilastik
- salford_systems
- menpo
- conda-forge
- defaults
dependencies:
- blas=1.1=openblas
- ca-certificates=2017.7.27.1=0
- certifi=2017.7.27.1=py35_0
- colorama=0.3.9=py35_0
- eigen=3.3.3=0
- gmp=6.1.2=0
#- gst-plugins-base=1.8.0=0
#- gstreamer=1.8.0=0
- h5py=2.7.0=np113py35_1
- hdf5=1.8.18=1
- isl=0.17.1=0
- jpeg=9b=0
- lapack=3.6.1=1
- libffi=3.2.1=1
- libiconv=1.14=0
- libxcb=1.12=1
- mpc=1.0.3=0
- ncurses=5.9=10
- numpy=1.13.1=py35_blas_openblas_200
- openblas=0.2.19=2
- openssl=1.0.2l=0
- pygments=2.2.0=py35_0
- pyqt=5.6.0
- python=3.5.4
- scipy=0.19.1=py35_blas_openblas_202
- setuptools=27.2.0=py35_0
- sip=4.18=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- wheel=0.29.0=py35_0
- xorg-libxau=1.0.8=3
- xorg-libxdmcp=1.1.2=3
- zlib=1.2.8=3
- configobj=5.0.6=py35_0
- dbus=1.10.22=0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- glib=2.50.2=1
- icu=54.1=0
#- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libpng=1.6.27=0
- libxml2=2.9.4=0
- pcre=8.39=1
- pip=9.0.1=py35_1
- qt=5.6.2
- readline=6.2=2
- tk=8.5.18=0
- xz=5.2.2=1
- binutils=2.26=0
- apptools=4.4.0=py35_0
- envisage=4.5.1=py35_0
- mayavi=4.5.0=py35_0
- pyface=5.1.0=py35_0
- traits=4.5.0=py35_0
- traitsui=5.1.0=py35_0
- vtk=7.0.0=py35_0
- expat=2.1.0=0
- gcc-6=6.2.0=0
- libgcc-6=6.2.0=2
- mpfr=3.1.5

