case:
    name: optimiser_0
    output_folder: ./output/
base:
    name: base
    route: ./base_case/
    generate_file: generate.py

settings:
    delete_case_folders: false
    cases_folder: ./cases/
    save_data: true

optimiser:
    numerics:
        tolerance: 0.01 
        n_iter: 30
        batch_size: 5
        n_cores: 20
        initial_design_numdata: 10
    parameters:
        0: acceleration
        1: dAoA
        2: ramp_angle
        3: release_velocity
    parameters_initial:
        0: 2.0
        1: 0.1
        2: 0.0
        3: 9.5
    parameters_bounds:
        0: [1.5, 5.0]
        1: [-1.0, 3.0]
        2: [-1.0, 5.0]
        3: [8.0, 15.0]
    cost:
        ground_clearance:
            z_min: -3
            z_0: 3
            scale: 10
        loads:
            reference_loads: 'input/cruise_loads.csv'
            Torsion:
                scale: 2
            OOP:
                scale: 2
            IP:
                scale: 2
    constraints:
        ramp_length: 20.0
        incidence_angle:
            limit: 9.0
            base_aoa: 4.09

